sy.init_printing(use_latex=True)
x,y,z = symbols('x,y,z')
print("Recuerda solo usar x,y,z en minúsculas para tus variables")
f = input("Ingresa los valores: ")
print("")
print("La Solucion de tu integral:")
sy.integrate(f, x)
print("la integral insertada")
print("")
sy.Integral(f, x)
